<h1><b>Statistique en Bioinformatique : </b> TME 5 et 6 </h1>
<br>
L’objectif de ce TME est:
<br>
<ul>
<li> implémenter l'algorithme de Viterbi et l'estimation des paramètres (en utilisant le Viterbi training)
pour l'exemple du occasionally dishonest casino.   </li> 
</ul>
<br>
<div class="alert alert-warning" role="alert" style="margin: 10px">
<p><b>Soumission</b></p>
<ul>
<li>Renomer le fichier TME5_6.ipynb pour TME_5_6_NomEtudiant1_NomEtudiant2.ipynb </li>
<li>Soumettre via moodle </li>
</div>
</div>

Nom etudiant 1 : NICOLAS Elise
<br>
Nom etudiant 2 : ANTON Christine
<br>

### Introduction
Un casino parfois malhonnête (*occasionally dishonest casino*) utilise 2 types de pièces : **fair** et **unfair**.

Hidden States: S = \{F,U\} (Fair, Unfair)

La matrice de transition entre les états cachés est :

P =
\begin{pmatrix}
0.99 & 0.01 \\
0.05 & 0.95
\end{pmatrix}


<br> Et la condition initiale $\pi^{(0)} = (0.999,0.001)$ 
Le jeux commence presque toujours avec le pieces juste (fair).


Obserations/Symbols: O = {H,T} (head, tail):

Les probabilités d'émission des symboles:

\begin{aligned}
e_F(H) &= 0.5 \quad & e_F(T) &= 0.5 \\
e_U(H) &= 0.9 \quad & e_U(T) &= 0.1
\end{aligned}

<b>Exercice 1</b>:
<u>Simulation</u>: Écrire une fonction qui simule $T$ jets de pièces. 
La fonction renverra un tableau à deux colonnes correspondant 
aux valeurs simulées pour les états cachés $X_t$ 
(type de dés utilisée, “F” ou “U”) et aux symboles observées $Y_t$ 
(résultat du jet de dés, “H” ou “T”). On simulera une séquence
de longueur 2000 qu'on gardera pour les applications ultérieures.


In [2]:
import numpy as np
import matplotlib.pyplot as plt

#states
S = { 0:'F',1 :'U'}

#transition probability matrix
Pij = np.array([[0.99,0.01], [0.05,0.95]])

#emision symbols 
O = {0:'H', 1: 'T'}

#emission probability matrix
Ei = np.array([[0.5,0.5], [0.9,0.1]]) #ça aurait dû être Eio

# initial Condition
pi0=np.array([0.999,0.001])

#number of jets
T = 2000

In [10]:
import random


# Fonction qui simule T jets de pieces
def jets(T, pi0, Ei, Pij):
    """
      simulation of occasionally dishonest casino
      input1 T: number of jets
      input2 pi0: initial condition
      input3 Ei: emission probability matrix
      input4 Pij: transition probability matrix
      output1 jetsRes: matrix |TxN_states| containing simulations
    """

    # Creation du tableau
    jetsRes = np.zeros((T, len(Pij)),dtype=int)
    curr_state = 0

    # Initial state
    prev_state = random.randint(0,1) # 0=fair, 1=unfair

    for t in range (T) : 
        # Get state
        r = random.random()
        if r<=Pij[prev_state][0] : 
            curr_state = 0
        else : 
            curr_state = 1
        jetsRes[t, 0] = curr_state
        prev_state = curr_state

        # Get observation
        e = random.random()
    
        if e<=Ei[curr_state, 0] : 
            curr_obs = 0
        else : 
            curr_obs = 1
        jetsRes[t, 1] = curr_obs
        

    return jetsRes


def printSimulation(simulation):
    for t in simulation : 
        print (t[0], t[1])


jetsRes = jets(T, pi0, Ei, Pij)
printSimulation(jetsRes)

0 1
0 0
0 1
0 1
0 1
0 0
0 0
0 1
0 1
0 0
0 1
0 0
0 0
0 1
0 0
0 1
0 0
0 0
0 1
0 1
0 0
0 0
0 1
0 0
0 0
0 1
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 1
0 1
0 1
0 0
0 1
0 0
0 0
0 1
0 1
0 0
0 0
0 1
0 0
0 0
0 1
0 1
0 1
0 1
0 0
0 0
0 0
0 1
0 0
0 0
0 0
0 1
0 0
0 0
0 1
0 1
0 1
0 0
0 0
0 1
0 0
0 0
0 0
0 1
0 1
0 0
0 0
0 0
0 1
0 1
0 1
0 0
0 0
0 1
0 0
0 1
0 1
0 1
0 0
0 1
0 1
0 0
0 1
0 1
0 1
0 0
0 1
0 0
0 0
0 0
0 1
0 1
0 0
0 0
0 1
0 1
0 1
0 0
0 0
0 1
0 1
0 1
0 1
0 0
0 1
0 1
0 0
0 1
0 0
0 0
0 1
0 0
0 1
0 0
0 1
0 1
0 1
0 0
0 0
0 1
0 0
0 0
0 1
0 0
0 1
0 0
0 1
0 1
0 1
0 1
0 1
0 0
0 0
0 1
0 0
0 1
0 1
0 0
0 1
0 1
0 1
0 0
0 0
0 0
0 0
0 1
0 0
0 0
0 1
0 1
0 1
0 1
0 0
0 0
0 1
0 1
0 1
0 1
0 0
0 0
0 1
0 1
0 1
0 1
0 0
0 0
0 1
0 1
0 1
0 0
0 0
0 1
0 0
0 1
0 0
0 1
0 0
0 1
0 0
0 1
0 1
0 1
0 0
0 0
0 0
0 1
0 1
0 1
0 0
0 1
0 0
0 1
0 0
0 1
0 1
0 0
0 0
0 0
0 0
0 1
0 0
0 1
0 0
0 0
0 0
0 1
0 1
0 1
0 1
0 1
0 1
0 0
0 0
0 0
0 1
0 0
0 1
0 1
0 0
0 0
0 1
0 1
0 0
1 0
1 0
1 0
1 0
1 0
1 1
1 0
1 0
0 0
0 1
1 0
0 1
1 0
1 0
1 0
1 0
1 0
1 1
1 0
1 0


<b>Exercice 2</b>: <u>Algorithme de Viterbi </u>: Écrire une fonction qui permet
de déterminer la séquence $(i^\star_t)_{t=0:T}$ d'états cachés
plus probable, ainsi que sa probabilité. En tant qu'observations, utiliser le résultat de la 
simulation (2éme colonne) de la question 1. Comparer $(i^\star_t)_{t=0:T}$ avec
les vrais états cachés (1ère colonne de la simulation).


In [11]:
# Algorithme de Viterbi
import operator

def viterbi(simulations, Pij, Ei, pi0, enLog):
    """
    Implement Viterbi algorithm
    input1 simulations: matrix |TxN_states| containing simulations
    input4 Pij: transition probability matrix
    input3 Ei: emission probability matrix
    input4 pi0: initial condition
    input6 enLog: bool, when True we apply log to avoid underflow
    output1 i_star: most problable path
    output2 prob: probability associated to the most problable path
    """

    obs = simulations[:,1]
    nS = len(Pij) #Nombre d'états
    T = len(obs) #Nombre d'observations (longueur des observations)

    i_star = np.zeros((T))
    prob = 1
    
    # Initialization
    delta_t = []
    psi_t = []
    for s in range(nS) :
        if enLog :
            delta_t.append(np.log(pi0[s]) + np.log(Ei[s, obs[0]]))
        else :
            delta_t.append(pi0[s]*Ei[s, obs[0]])
        psi_t.append(0)
    delta = [delta_t]
    psi = [psi_t]

    # Recursion
    for t in range(1,T) :
        delta_t = []
        psi_t = []
        delta_prec = delta[t-1]
        curr_obs = obs[t]
        
        for i in range(nS) : 
            temp = []
            for j in range(nS) :
                if enLog :
                    temp.append(delta_prec[j] + np.log(Pij[j, i]))
                else :
                    temp.append(delta_prec[j]*Pij[j, i])
            m = max(temp)
            if enLog : 
                delta_t.append(m + np.log(Ei[i, curr_obs]))
            else : 
                delta_t.append(m*Ei[i, curr_obs])
            psi_t.append(temp.index(m))
        delta.append(delta_t)
        psi.append(psi_t)
  
    # Termination / Traceback
    i_star[T-1] = delta[T-1].index(max(delta[T-1]))
    prob = max(delta[T-1])
    for t in range(T-2, -1, -1):  # Parcours à rebours
        i_star[t] = psi[t+1][int(i_star[t+1])]
    # for t in range(0, T-2, -1) :
    #     i_star[t] = psi[t][i_star[t]]
        
    return i_star, prob

def analyseResultats(simulations, estimation):    
    """
    Compare expected and obtained paths
    input1 simulations: expected path
    input2 estimation: obtained path
    output1 error: percentage error
    """
    expected = np.array(simulations[:,0])
    count = np.sum(np.where(expected != estimation, 1, 0))
    error = count/len(simulations)*100
    return error


i_est, p_est = viterbi(jetsRes, Pij, Ei, pi0, False)
error = analyseResultats(jetsRes, i_est)
print('erreur d\'estimation de viterbi:')
print(error,'%')
print('Probabilité estimé:')
print(p_est)

i_est, p_est = viterbi(jetsRes,Pij,Ei,pi0,True)
error = analyseResultats(jetsRes, i_est)
print('erreur d\'estimation de viterbi:')
print(error,'%')
print('Probabilité estimé:')
print(p_est)


erreur d'estimation de viterbi:
6.75 %
Probabilité estimé:
0.0
erreur d'estimation de viterbi:
4.2 %
Probabilité estimé:
-1383.7062748206592


<b>Exercice 3</b>: <u>Estimation des paramètres</u>
<br>
3.1) Écrire une fonction qu'utilise tous les résultats de la simulation
(états et symboles) pour estimer $P_{ij}$, $E_i(O)$ et pi_0. Attention, pour éviter les probabilités à zéro nous allons utiliser les pseudo-count.

In [13]:
# Estimation de Parametres par contage
def nombresOccurrence(simulation, nS, nO):
    """
    Parameter estimation
    input1 simulation: matrix |TxN_states| containing data
    input2 nS: number of states
    input3 nO: number of observations
    output1 Pij_est: transition probability matrix
    output2 Ei_est: emission probability matrix
    output3 pi0_est: initial condition 
    """

    Pij_est = np.ones((nS,nS)) #pseudo-count = 1
    Ei_est = np.ones((nS,nO))  #pseudo-count = 1
    Ei_est[simulation[0, 0], simulation[0, 1]] += 1
    pi0_est = np.ones(nS)

    etat_seq = simulation[:,0]
    obs_seq = simulation[:,1]
    T = len(obs_seq)

    # estimate Pij_est and Ei_est using frequency ...
    for t in range(1, T) :
        # Transition probability
        etat_curr = simulation[t, 0]
        etat_prec = simulation[t-1, 0]
        Pij_est[etat_prec, etat_curr]+=1

        # Emission probability
        obs_curr = simulation[t, 1]
        Ei_est[etat_curr, obs_curr]+=1

    # Normalisation
    Pij_est = Pij_est/np.sum(Pij_est, axis=1)[:, np.newaxis]
    Ei_est = Ei_est/np.sum(Ei_est, axis=1)[:, np.newaxis]

    # to estimate pi0_est
    pi0_est = np.ones((nS)) / 1000 # Il n'y a pas assez d'informations pour π
    pi0_est[etat_seq[0]] = 0.999  # On doit répéter le procès de génération de séquence de plusieurs fois pour obtenir le meilleur π
    
    # normalize Pij_est, Ei_est, pi0_est .....

    return Pij_est, Ei_est, pi0_est


Pij_est, Ei_est ,pi0_est = nombresOccurrence(jetsRes,2,2)

print('Pij estimé:')
print(Pij_est)
print('\nEio estimé:')
print(Ei_est)
print('\npi0 estimé:')
print(pi0_est)

Pij estimé:
[[0.99207697 0.00792303]
 [0.05508475 0.94491525]]

Eio estimé:
[[0.47198642 0.52801358]
 [0.85654008 0.14345992]]

pi0 estimé:
[0.999 0.001]


3.2) <u> Viterbi training </u>: Écrire une fonction qui utilise
seulement la séquence $(O_t)_{t=0:T}$ (2emme colonne de la simulation) pour estimer les
paramètres $P_{ij}$ est $Ei(O)$. On s’arrêtera quand les différences entre les logVraissamblance est inférieur à 1e-04. Comparer les résultats de 3.1 et de 3.2 (3.2 avec plusieurs restarts,
et avec initialisation des paramètres aléatoire).


In [ ]:
import matplotlib.pyplot as plt

# Initialisation aleatoire de Pij, Eij, pi0
def InititRandom(nS, nO):
    """
    randomly initialisations 
    input1 nS: number of states
    input2 nO: number of observations
    output1 Pij_init: transition probability matrix
    output2 Ei_init: emission probability matrix
    output3 pi0_init: initial condition 
    """
    random.seed(10)
    
    Pij_init = np.random.rand(nS, nS)
    Ei_init = np.random.rand(nS, nO)
    pi0_init = np.random.rand(nS)

    return Pij_init, Ei_init, pi0_init

# Calcule log Vraissamblance
def logLikelhihood(Pij_est,Eij_est,pi0_est,jets_est):
    """
    compute Log Likelihood 
    input1 Pij: transition probability matrix
    input2 Ei: emission probability matrix
    input3 pi0: initial condition 
    input4 jets: matrix |Tx2| containing data
    """
    etat_seq = jets_est[:,0]
    obs_seq = jets_est[:,1]
    T = len(obs_seq) #Nombre d'observations (longueur des observations)
    LL = np.log(pi0_est[etat_seq[0]]) + np.log(Eij_est[etat_seq[0]][obs_seq[0]])
 
    for t in range(1, T) : 
        etat_curr = jets_est[t, 0]
        etat_prec = jets_est[t-1, 0]
        obs_curr = jets_est[t, 1]
        LL+= np.log(Pij_est[etat_prec, etat_curr]) + np.log(Eij_est[etat_curr, obs_curr])

    return LL


def Training(jets, nS, nO):
    """
    Viterbi Training
    input1 jets: matrix |Tx2| containing data
    input2 nS: number of states
    input3 nO: number of observations
    output1 Pij_est: transition probability matrix
    output2 Ei_est: emission probability matrix
    output3 pi0_est: initial condition 
    output4 lLikelihood: log Likelihood
    """
    jets_est = np.array(jets)    
    Pij_est, Eij_est, pi0_est = InititRandom(nS, nO)
    
    maxIteration = 10000
    stopping_criterion = 1e-04 # the algo stops when the absolute difference between two consequtive likelihood calculation is lass then soppring_criteirion
    LL = [0]
   
    for iCount in range (maxIteration) :
        print(iCount)
        new_Pij_est, new_Eij_est, new_pi0_est = nombresOccurrence(jets_est, nS, nO)
        new_LL = logLikelhihood(new_Pij_est, new_Eij_est, new_pi0_est, jets_est)

        if np.abs(LL[iCount-1]-new_LL) < stopping_criterion : 
            return Pij_est, Eij_est, pi0_est, LL

        LL.append(new_LL)
        Pij_est = new_Pij_est
        Eij_est = new_Eij_est
        pi0_est = new_pi0_est
        
    return Pij_est, Eij_est, pi0_est, np.array(LL)
    
#imprimer les Parametres du Viterbi Training
Pij_est, Ei_est, pi0_est, lLikelihood = Training(jetsRes, 2, 2)
itCount = len(lLikelihood)
print('Le modèle est convergé après '+str(itCount)+' itérations.')
print('\nPij estimée:')
print(Pij_est)
print('\nEij estimée:')
print(Ei_est)

0
1
2
Le modèle est convergé après 3 itérations.

Pij estimée:
[[0.99207697 0.00792303]
 [0.05508475 0.94491525]]

Eij estimée:
[[0.47198642 0.52801358]
 [0.85654008 0.14345992]]


<font color="blue">
Remark:
</font>

3.3) <u>Viterbi training deuxième version</u>. 
<BR>Écrivez une version de 3.2 qui:
- part plusieurs fois (100x) d'une initialisation aléatoire desparamètres de l'HMM,
- utilise Viterbi training pour estimer les paramètres,
- calcul la log-vraisemblance pour les paramètres estimés,
- sauvegarde seulement l'estimation avec la valeur maximale de lalog-vraisemblance.

Qu'est-ce que vous observez?



In [22]:
# Viterbi Training  deuxiemme version

def TrainingV2(jets, nS, nO, nIterat=100):
    """
    Viterbi Training version 2.0
    input1 jets: matrix |TxN_states| containing data
    input2 nS: number of states
    input3 nO: number of observations
    input4 nIterat: number of iterations
    output1 Pij_best: best transition probability matrix
    output2 Ei_best: best emission probability matrix
    output3 pi0_best: best initial condition 
    output4 lLikelihood_best: best log Likelihood
    """

    Pij_best = []
    Ei_best = []
    pi0_best = []
    lLikelihood_best = -10000
    for nIter in range(nIterat) :
        Pij_est, Ei_est, pi0_est, lLikelihood = Training(jets, nS, nO)
        LL = lLikelihood[-1]
        if LL > lLikelihood_best : 
            lLikelihood_best = LL
            Pij_best, Ei_best, pi0_best = Pij_est, Ei_est, pi0_est

    return Pij_best, Ei_best, pi0_best, lLikelihood_best
    

# Imprimer les Parametres du Viterbi Training deuxiemme version
nIterat = 100
Pij_best, Ei_best, pi0_best, lLikelihood_best = TrainingV2(jetsRes, 2, 2, nIterat)

print('Meilleur Pij estimée:');
print(Pij_best)
print('\nMeilleur Eij estimée:')
print(Ei_best)

0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
Meilleur Pij estimée:
[[0.99207697 0.00792303]
 [0.05508475 0.94491525]]

Meilleur Eij estimée:
[[0.47198642 0.52801358]
 [0.85654008 0.14345992]]


<font color="blue">
Remark:
</font>